import { Inter } from "next/font/google";
import Script from "next/script";
import Loader from "@/components/Common/Loader";
import Wrapper from "../components/layout/Wrapper";
import {
  getCategoriesData,
  getCollectionsData,
  getFooterData,
  getFooterLinksData,
  getHomeBottomRightSocialLinks,
  getHomePageData,
} from "@/services/apiServices";
import Navbar from "@/components/Common/Navbar";
import Footer from "@/components/Common/Footer";

import "../../public/assets/utils.css";
import "../../public/assets/app.css";
import Account from "@/components/Account/Index";
import Head from "@/head";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Blueprint Studios | F1 Las Vegas Grand Prix",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, navbar }) {
  const collectionsData = await getCollectionsData();
  const selectedCollections = collectionsData.map((x) => x._id);

  const [
    homePageData,
    categoriesData,
    footerData,
    footerLinksData,
    footerBottomRightSocialLinks,
  ] = await Promise.all([
    getHomePageData(),
    getCategoriesData(selectedCollections),
    getFooterData(),
    getFooterLinksData(),
    getHomeBottomRightSocialLinks(),
  ]);
  return (
    <>
      <Script type="module" rel="modulepreload" src="/assets/loader.js" />
      <Script type="module" rel="modulepreload" src="/assets/app2.js" />
      <Script
        type="module"
        rel="modulepreload"
        src="/assets/product-link-color.js"
      />
      <Script type="module" rel="modulepreload" src="/assets/pjax.js" />
      <Script type="module" rel="modulepreload" src="/assets/data-set-get.js" />
      <Script type="module" rel="modulepreload" src="/assets/screen-size.js" />
      <Script type="module" rel="modulepreload" src="/assets/navigation.js" />
      <Script
        type="module"
        rel="modulepreload"
        src="/assets/product-content.js"
      />
      <Script
        type="module"
        rel="modulepreload"
        src="/assets/cancel-product.js"
      />
      <Script type="module" rel="modulepreload" src="/assets/form-cart.js" />
      <Script type="module" rel="modulepreload" src="/assets/form-sign-in.js" />
      <Script type="module" rel="modulepreload" src="/assets/forms.js" />
      <Script type="module" rel="modulepreload" src="/assets/collections.js" />
      <Script
        type="module"
        rel="modulepreload"
        src="/assets/filter-products.js"
      />

      <Script type="module" src="/assets/loader.js"></Script>
      <Script type="module" src="/assets/app2.js"></Script>
      <Script type="module" src="/assets/product-content.js"></Script>
      <Script type="module" src="/assets/cancel-product.js"></Script>
      <Script type="module" src="/assets/form-cart.js"></Script>
      <Script type="module" src="/assets/form-sign-in.js"></Script>
      <Script type="module" src="/assets/forms.js"></Script>
      <Script type="module" src="/assets/collections.js"></Script>
      <Script type="module" src="/assets/filter-products.js"></Script>

      <html lang="en">
        <body
          data-scroll-direction="initial"
          data-load="first-loading"
          class="overflow-hidden"
        >
          <span className="initScript d-none"></span>
          <span className="initializeCanvas d-none"></span>
          <span className="home d-none"></span>
          <span className="updateWatched d-none"></span>
          <span className="galleryLightBox d-none"></span>
          <span className="collections d-none"></span>
          <span className="products d-none"></span>
          <span className="productsPost d-none"></span>
          <span className="cartPage d-none"></span>
          <span className="myAccount d-none"></span>
          <span className="savedProducts d-none"></span>
          <span className="quotesHistory d-none"></span>
          <span className="changePassword d-none"></span>
          <span className="galleryImages d-none"></span>
          <span className="addToCart d-none"></span>
          <span className="modalLoad d-none"></span>

          <Loader />
          <Navbar
            homePageData={homePageData}
            collectionsData={collectionsData}
            categoriesData={categoriesData}
          />
          <Account />
          <Wrapper>
            <main>{children}</main>
          </Wrapper>
          <Footer
            footerData={footerData}
            footerLinksData={footerLinksData}
            socialLinks={footerBottomRightSocialLinks}
          />
        </body>
      </html>
    </>
  );
}
