import { Inter } from "next/font/google";
import Loader from "@/components/Common/Loader";
import Wrapper from "../components/layout/Wrapper";
import {
  getCategoriesData,
  getCollectionsData,
  getFooterData,
  getFooterLinksData,
  getHomeBottomRightSocialLinks,
  getHomePageData,
} from "@/services/apiServices";
import Navbar from "@/components/Common/Navbar";
import Footer from "@/components/Common/Footer";

import "../../public/assets/utils.css";
import "../../public/assets/app.css";
import Account from "@/components/Account/Index";
import { Suspense } from "react";
import CustomScripts from "@/services/CustomScripts";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Blueprint Studios | F1 Las Vegas Grand Prix",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, navbar }) {
  const collectionsData = await getCollectionsData();
  const selectedCollections = collectionsData.map((x) => x._id);

  const [
    homePageData,
    categoriesData,
    footerData,
    footerLinksData,
    footerBottomRightSocialLinks,
  ] = await Promise.all([
    getHomePageData(),
    getCategoriesData(selectedCollections),
    getFooterData(),
    getFooterLinksData(),
    getHomeBottomRightSocialLinks(),
  ]);
  function SearchBarFallback() {
    return <>Loading</>;
  }

  return (
    <>
      <CustomScripts />
      <html lang="en">
        <body
          data-scroll-direction="initial"
          data-load="first-loading"
          class="overflow-hidden"
        >
          <span className="initScript d-none"></span>
          <span className="initializeCanvas d-none"></span>
          <span className="home d-none"></span>
          <span className="updateWatched d-none"></span>
          <span className="galleryLightBox d-none"></span>
          <span className="collections d-none"></span>
          <span className="products d-none"></span>
          <span className="productsPost d-none"></span>
          <span className="cartPage d-none"></span>
          <span className="myAccount d-none"></span>
          <span className="savedProducts d-none"></span>
          <span className="quotesHistory d-none"></span>
          <span className="changePassword d-none"></span>
          <span className="galleryImages d-none"></span>
          <span className="addToCart d-none"></span>
          <span className="modalLoad d-none"></span>

          <Loader />
          <Suspense fallback={<SearchBarFallback />}>
            <Navbar
              homePageData={homePageData}
              collectionsData={collectionsData}
              categoriesData={categoriesData}
            />
          </Suspense>
          <Account />
          <Wrapper>
            <main>{children}</main>
          </Wrapper>
          <Footer
            footerData={footerData}
            footerLinksData={footerLinksData}
            socialLinks={footerBottomRightSocialLinks}
          />
        </body>
      </html>
    </>
  );
}
