import { Inter } from "next/font/google";
import "./globals.css";
import "../../public/assets/utils.css";
import "../../public/assets/app.css";
import Loader from "@/components/Loader";
import Script from "next/script";
import Navbar from "@/layout/Navbar";
import createWixClient from "@/config/WixConfig";
import { headers } from "next/headers";

const WixClient = createWixClient();

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const getHomePageData = async () => {
  try {
    let options = {
      dataCollectionId: "HomePageData_f1",
    };
    const { items: fetchHomeData } = await WixClient.items
      .queryDataItems(options)
      .find();

    return fetchHomeData[0].data;
  } catch (error) {
    throw new Error(error.message);
  }
};

export default async function RootLayout({ children }) {
  const homePageData = await getHomePageData();
  const headersList = headers();
  const referer = headersList.get("referer");
  const url = new URL(referer);
  const pathname = url.pathname.substring(1); // Remove the leading '/'

  console.log("PATHNAME", pathname);
  return (
    <>
      <Script type="module" rel="modulepreload" src="/assets/loader.js" />
      <Script type="module" rel="modulepreload" src="/assets/app2.js" />
      <Script
        type="module"
        rel="modulepreload"
        src="/assets/product-link-color.js"
      />
      <Script type="module" rel="modulepreload" src="/assets/pjax.js" />
      <Script type="module" rel="modulepreload" src="/assets/data-set-get.js" />
      <Script type="module" rel="modulepreload" src="/assets/screen-size.js" />
      <Script type="module" rel="modulepreload" src="/assets/navigation.js" />
      <Script
        type="module"
        rel="modulepreload"
        src="/assets/product-content.js"
      />
      <Script
        type="module"
        rel="modulepreload"
        src="/assets/cancel-product.js"
      />
      <Script type="module" rel="modulepreload" src="/assets/form-cart.js" />
      <Script type="module" rel="modulepreload" src="/assets/form-sign-in.js" />
      <Script type="module" rel="modulepreload" src="/assets/forms.js" />
      <Script type="module" rel="modulepreload" src="/assets/collections.js" />
      <Script
        type="module"
        rel="modulepreload"
        src="/assets/filter-products.js"
      />

      <Script type="module" src="/assets/loader.js"></Script>
      <Script type="module" src="/assets/app2.js"></Script>
      <Script type="module" src="/assets/product-content.js"></Script>
      <Script type="module" src="/assets/cancel-product.js"></Script>
      <Script type="module" src="/assets/form-cart.js"></Script>
      <Script type="module" src="/assets/form-sign-in.js"></Script>
      <Script type="module" src="/assets/forms.js"></Script>
      <Script type="module" src="/assets/collections.js"></Script>
      <Script type="module" src="/assets/filter-products.js"></Script>
      <html lang="en">
        <body
          className={inter.className}
          data-scroll-direction="initial"
          data-load="first-loading"
          class="overflow-hidden"
        >
          <span class="initScript d-none"></span>
          <span class="home d-none"></span>
          <span class="updateWatched d-none"></span>
          <span class="galleryLightBox d-none"></span>
          <span class="products d-none"></span>
          <span class="productsPost d-none"></span>
          <span class="cartPage d-none"></span>
          <span class="savedProducts d-none"></span>
          <span class="quotesHistory d-none"></span>
          <span class="galleryImages d-none"></span>
          <span class="updateWatched d-none"></span>
          <Loader />
          <Navbar homePageData={homePageData} />
          <div id="main-transition">
            <div
              id={`pg-${pathname}`}
              className="wrapper"
              data-scroll-container
            >
              <main>{children}</main>
            </div>
          </div>
        </body>
      </html>
    </>
  );
}
