export const BestSeller = {
  "TRADESHOWS BEST SELLERS": "TRADESHOWS BEST SELLERS",
  "TRADESHOWS BEST SELLERS": "TRADESHOWS BEST SELLERS",
  "SOCIAL BEST SELLERS": "SOCIAL BEST SELLERS",
  "CORPORATE BEST SELLERS": "CORPORATE BEST SELLERS",
};
