export function hexToColorName(hex) {
  hex = hex.toLowerCase();
  const colorMap = {
    "#000000": "Black",
    "#000080": "Navy",
    "#00008b": "DarkBlue",
    "#0000cd": "MediumBlue",
    "#0000ff": "Blue",
    "#006400": "DarkGreen",
    "#008000": "Green",
    "#008080": "Teal",
    "#008b8b": "DarkCyan",
    "#00bfff": "DeepSkyBlue",
    "#00ced1": "DarkTurquoise",
    "#00fa9a": "MediumSpringGreen",
    "#00ff00": "Lime",
    "#00ff7f": "SpringGreen",
    "#00ffff": "Cyan",
    "#191970": "MidnightBlue",
    "#1e90ff": "DodgerBlue",
    "#20b2aa": "LightSeaGreen",
    "#228b22": "ForestGreen",
    "#2e8b57": "SeaGreen",
    "#2f4f4f": "DarkSlateGray",
    "#32cd32": "LimeGreen",
    "#3cb371": "MediumSeaGreen",
    "#40e0d0": "Turquoise",
    "#4169e1": "RoyalBlue",
    "#4682b4": "SteelBlue",
    "#483d8b": "DarkSlateBlue",
    "#48d1cc": "MediumTurquoise",
    "#4b0082": "Indigo",
    "#556b2f": "DarkOliveGreen",
    "#5f9ea0": "CadetBlue",
    "#6495ed": "CornflowerBlue",
    "#663399": "RebeccaPurple",
    "#66cdaa": "MediumAquaMarine",
    "#696969": "DimGray",
    "#6a5acd": "SlateBlue",
    "#6b8e23": "OliveDrab",
    "#708090": "SlateGray",
    "#778899": "LightSlateGray",
    "#7b68ee": "MediumSlateBlue",
    "#7cfc00": "LawnGreen",
    "#7fff00": "Chartreuse",
    "#7fffd4": "Aquamarine",
    "#800000": "Maroon",
    "#800080": "Purple",
    "#808000": "Olive",
    "#808080": "Gray",
    "#87ceeb": "SkyBlue",
    "#87cefa": "LightSkyBlue",
    "#8a2be2": "BlueViolet",
    "#8b0000": "DarkRed",
    "#8b008b": "DarkMagenta",
    "#8b4513": "SaddleBrown",
    "#8fbc8f": "DarkSeaGreen",
    "#90ee90": "LightGreen",
    "#9370db": "MediumPurple",
    "#9400d3": "DarkViolet",
    "#98fb98": "PaleGreen",
    "#9932cc": "DarkOrchid",
    "#9acd32": "YellowGreen",
    "#a0522d": "Sienna",
    "#a52a2a": "Brown",
    "#a9a9a9": "DarkGray",
    "#add8e6": "LightBlue",
    "#adff2f": "GreenYellow",
    "#afeeee": "PaleTurquoise",
    "#b0c4de": "LightSteelBlue",
    "#b0e0e6": "PowderBlue",
    "#b22222": "FireBrick",
    "#b8860b": "DarkGoldenrod",
    "#ba55d3": "MediumOrchid",
    "#bc8f8f": "RosyBrown",
    "#bdb76b": "DarkKhaki",
    "#c0c0c0": "Silver",
    "#c71585": "MediumVioletRed",
    "#cd5c5c": "IndianRed",
    "#cd853f": "Peru",
    "#d2691e": "Chocolate",
    "#d2b48c": "Tan",
    "#d3d3d3": "LightGray",
    "#d8bfd8": "Thistle",
    "#da70d6": "Orchid",
    "#daa520": "Goldenrod",
    "#db7093": "PaleVioletRed",
    "#dc143c": "Crimson",
    "#dcdcdc": "Gainsboro",
    "#dda0dd": "Plum",
    "#deb887": "BurlyWood",
    "#e0ffff": "LightCyan",
    "#e6e6fa": "Lavender",
    "#e9967a": "DarkSalmon",
    "#ee82ee": "Violet",
    "#eee8aa": "PaleGoldenrod",
    "#f08080": "LightCoral",
    "#f0e68c": "Khaki",
    "#f0f8ff": "AliceBlue",
    "#f0fff0": "Honeydew",
    "#f0ffff": "Azure",
    "#f4a460": "SandyBrown",
    "#f5deb3": "Wheat",
    "#f5f5dc": "Beige",
    "#f5f5f5": "WhiteSmoke",
    "#f5fffa": "MintCream",
    "#f8f8ff": "GhostWhite",
    "#fa8072": "Salmon",
    "#faebd7": "AntiqueWhite",
    "#faf0e6": "Linen",
    "#fafad2": "LightGoldenrodYellow",
    "#fdf5e6": "OldLace",
    "#ff0000": "Red",
    "#ff00ff": "Fuchsia",
    "#ff1493": "DeepPink",
    "#ff4500": "OrangeRed",
    "#ff6347": "Tomato",
    "#ff69b4": "HotPink",
    "#ff7f50": "Coral",
    "#ff8c00": "DarkOrange",
    "#ffa07a": "LightSalmon",
    "#ffa500": "Orange",
    "#ffb6c1": "LightPink",
    "#ffc0cb": "Pink",
    "#ffd700": "Gold",
    "#ffdab9": "PeachPuff",
    "#ffdead": "NavajoWhite",
    "#ffe4b5": "Moccasin",
    "#ffe4c4": "Bisque",
    "#ffe4e1": "MistyRose",
    "#ffebcd": "BlanchedAlmond",
    "#ffefd5": "PapayaWhip",
    "#fff0f5": "LavenderBlush",
    "#fff5ee": "SeaShell",
    "#fff8dc": "Cornsilk",
    "#fffacd": "LemonChiffon",
    "#fffaf0": "FloralWhite",
    "#fffafa": "Snow",
    "#ffff00": "Yellow",
    "#ffffe0": "LightYellow",
    "#fffff0": "Ivory",
    "#ffffff": "White",
  };

  // Calculate the Euclidean distance between the colors
  function distance(color1, color2) {
    const deltaR = color1[0] - color2[0];
    const deltaG = color1[1] - color2[1];
    const deltaB = color1[2] - color2[2];
    return Math.sqrt(deltaR * deltaR + deltaG * deltaG + deltaB * deltaB);
  }

  const inputRgb = [
    parseInt(hex.substring(1, 3), 16),
    parseInt(hex.substring(3, 5), 16),
    parseInt(hex.substring(5, 7), 16),
  ];

  let closestColor = null;
  let minDistance = Infinity;
  for (const colorHex in colorMap) {
    const namedRgb = [
      parseInt(colorHex.substring(1, 3), 16),
      parseInt(colorHex.substring(3, 5), 16),
      parseInt(colorHex.substring(5, 7), 16),
    ];
    const dist = distance(inputRgb, namedRgb);
    if (dist < minDistance) {
      minDistance = dist;
      closestColor = colorMap[colorHex];
    }
  }

  return closestColor;
}
